/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CButton: typeof import('@chaosgods/ui')['Button']
    CInput: typeof import('@chaosgods/ui')['Input']
    CTooltip: typeof import('@chaosgods/ui')['Tooltip']
  }
}
